chore(deps): update dependency @orpc/server to v1.6.2 (#116)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [@orpc/server](https://orpc.unnoq.com)
([source](https://redirect.github.com/unnoq/orpc/tree/HEAD/packages/server))
| [`1.5.0` ->
`1.6.2`](https://renovatebot.com/diffs/npm/@orpc%2fserver/1.5.0/1.6.2) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/@orpc%2fserver/1.6.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@orpc%2fserver/1.6.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@orpc%2fserver/1.5.0/1.6.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@orpc%2fserver/1.5.0/1.6.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>unnoq/orpc (@&#8203;orpc/server)</summary>

###
[`v1.6.2`](https://redirect.github.com/unnoq/orpc/releases/tag/v1.6.2)

[Compare
Source](https://redirect.github.com/unnoq/orpc/compare/v1.6.1...v1.6.2)

#####    🐞 Bug Fixes

- **contract**: EventIterator should cleanup on validation failure  - 
by [@&#8203;unnoq](https://redirect.github.com/unnoq) in
[https://github.com/unnoq/orpc/issues/715](https://redirect.github.com/unnoq/orpc/issues/715)
[<samp>(40088)</samp>](https://redirect.github.com/unnoq/orpc/commit/40088212)

#####     [View changes on
GitHub](https://redirect.github.com/unnoq/orpc/compare/v1.6.1...v1.6.2)

###
[`v1.6.1`](https://redirect.github.com/unnoq/orpc/releases/tag/v1.6.1)

[Compare
Source](https://redirect.github.com/unnoq/orpc/compare/v1.6.0...v1.6.1)

#####    🚀 Features

- **nest**: Module configuration  -  by
[@&#8203;unnoq](https://redirect.github.com/unnoq) in
[https://github.com/unnoq/orpc/issues/710](https://redirect.github.com/unnoq/orpc/issues/710)
[<samp>(3d8a8)</samp>](https://redirect.github.com/unnoq/orpc/commit/3d8a81d5)

#####     [View changes on
GitHub](https://redirect.github.com/unnoq/orpc/compare/v1.6.0...v1.6.1)

###
[`v1.6.0`](https://redirect.github.com/unnoq/orpc/releases/tag/v1.6.0)

[Compare
Source](https://redirect.github.com/unnoq/orpc/compare/v1.5.2...v1.6.0)

##### Durable Event Iterator
[docs](https://orpc.unnoq.com/docs/integrations/durable-event-iterator)

Durable Event Iterator allows you to use [Event
Iterator](https://orpc.unnoq.com/docs/event-iterator) by separating the
streaming to a different service that provides durable event streams,
automatic reconnections, recovery of missing events, and more.

> \[!NOTE]
> Only support Cloudflare Websocket Hibernation for now

```ts
  const onMessageProcedure = base.handler(({ context }) => {
    return new DurableEventIterator<ChatRoom>('some-room', {
      signingKey: 'secret-key', // Replace with your actual signing key
    })
  })
```

##### oRPC features now support tRPC
[docs](https://orpc.unnoq.com/docs/openapi/integrations/trpc)

By converting a [tRPC router](https://trpc.io/docs/server/routers) to an
[oRPC router](https://orpc.unnoq.com/docs/router), you can utilize most
oRPC features, including OpenAPI specification generation and request
handling.

```ts
import {
  experimental_ORPCMeta as ORPCMeta,
  experimental_toORPCRouter as toORPCRouter
} from '@&#8203;orpc/trpc'

export const t = initTRPC.context<Context>().meta<ORPCMeta>().create()

const orpcRouter = toORPCRouter(trpcRouter)
```

#####    🚨 Breaking Changes

> \[!NOTE]
> Only effect **experimental features**

- **server**: Improve hibernation naming conventions  -  by
[@&#8203;unnoq](https://redirect.github.com/unnoq) in
[https://github.com/unnoq/orpc/issues/686](https://redirect.github.com/unnoq/orpc/issues/686)
[<samp>(add5a)</samp>](https://redirect.github.com/unnoq/orpc/commit/add5acf4)
- **standard-server-peer**: Use string instead of number for unique ID
 -  by [@&#8203;unnoq](https://redirect.github.com/unnoq) in
[https://github.com/unnoq/orpc/issues/682](https://redirect.github.com/unnoq/orpc/issues/682)
[<samp>(b683b)</samp>](https://redirect.github.com/unnoq/orpc/commit/b683b88f)

#####    🚀 Features

- **durable-event-iterator**: Implement event iterator with Cloudflare
hibernation and more  -  by
[@&#8203;unnoq](https://redirect.github.com/unnoq) in
[https://github.com/unnoq/orpc/issues/668](https://redirect.github.com/unnoq/orpc/issues/668)
[<samp>(ce855)</samp>](https://redirect.github.com/unnoq/orpc/commit/ce8559f0)
- **server**: Enhance call util to support signal and lastEventId
options  -  by [@&#8203;unnoq](https://redirect.github.com/unnoq) in
[https://github.com/unnoq/orpc/issues/687](https://redirect.github.com/unnoq/orpc/issues/687)
[<samp>(57b0b)</samp>](https://redirect.github.com/unnoq/orpc/commit/57b0b5d8)
- **trpc**: Trpc router to orpc router  -  by
[@&#8203;unnoq](https://redirect.github.com/unnoq) in
[https://github.com/unnoq/orpc/issues/699](https://redirect.github.com/unnoq/orpc/issues/699)
[<samp>(cf357)</samp>](https://redirect.github.com/unnoq/orpc/commit/cf3573de)
- **zod**: Place null at the end when converting ZodNullable  -  by
[@&#8203;soonoo](https://redirect.github.com/soonoo) in
[https://github.com/unnoq/orpc/issues/672](https://redirect.github.com/unnoq/orpc/issues/672)
[<samp>(8be95)</samp>](https://redirect.github.com/unnoq/orpc/commit/8be955f1)

#####    🐞 Bug Fixes

- **server**: Prevent reference issues in ResponseHeadersPlugin  -  by
[@&#8203;unnoq](https://redirect.github.com/unnoq) in
[https://github.com/unnoq/orpc/issues/693](https://redirect.github.com/unnoq/orpc/issues/693)
[<samp>(a1531)</samp>](https://redirect.github.com/unnoq/orpc/commit/a1531257)

#####     [View changes on
GitHub](https://redirect.github.com/unnoq/orpc/compare/v1.5.2...v1.6.0)

###
[`v1.5.2`](https://redirect.github.com/unnoq/orpc/releases/tag/v1.5.2)

[Compare
Source](https://redirect.github.com/unnoq/orpc/compare/v1.5.1...v1.5.2)

##### UndefinedError common schemas
[docs](https://orpc.unnoq.com/docs/openapi/openapi-specification)

`UndefinedError` is used for undefined errors, which is very useful when
using [Type-Safe Error
Handling](https://orpc.unnoq.com/docs/error-handling#type%E2%80%90safe-error-handling).

```ts
const spec = await generator.generate(router, {
  commonSchemas: {
    User: {
      schema: UserSchema,
    },
    UndefinedError: {
      error: 'UndefinedError'
    }
  },
})
```

#####    🚀 Features

- **openapi**: Support UndefinedError in commonSchemas for spec
generation  -  by [@&#8203;unnoq](https://redirect.github.com/unnoq) in
[https://github.com/unnoq/orpc/issues/655](https://redirect.github.com/unnoq/orpc/issues/655)
[<samp>(93fa2)</samp>](https://redirect.github.com/unnoq/orpc/commit/93fa264b)

#####    🐞 Bug Fixes

- **openapi**: Readonly for allowedStrategies and components in
SchemaConverter types  -  by
[@&#8203;unnoq](https://redirect.github.com/unnoq)
[<samp>(8b6cb)</samp>](https://redirect.github.com/unnoq/orpc/commit/8b6cb3ad)

#####     [View changes on
GitHub](https://redirect.github.com/unnoq/orpc/compare/v1.5.1...v1.5.2)

###
[`v1.5.1`](https://redirect.github.com/unnoq/orpc/releases/tag/v1.5.1)

[Compare
Source](https://redirect.github.com/unnoq/orpc/compare/v1.5.0...v1.5.1)

##### Common Schemas
[docs](https://orpc.unnoq.com/docs/openapi/openapi-specification#common-schemas)

Define reusable schema components that can be referenced across your
OpenAPI specification (Only support zod 3 and 4 for now):

```ts
const UserSchema = z.object({
  id: z.string(),
  name: z.string(),
  email: z.string().email(),
})

const PetSchema = z.object({
  id: z.string().transform(id => Number(id)).pipe(z.number()),
})

const spec = await generator.generate(router, {
  commonSchemas: {
    User: {
      schema: UserSchema,
    },
    InputPet: {
      strategy: 'input',
      schema: PetSchema,
    },
    OutputPet: {
      strategy: 'output',
      schema: PetSchema,
    },
  },
})
```

#####    🚀 Features

- **openapi**: Gen spec with common schemas - `components.schemas`  - 
by [@&#8203;unnoq](https://redirect.github.com/unnoq) in
[https://github.com/unnoq/orpc/issues/638](https://redirect.github.com/unnoq/orpc/issues/638)
[<samp>(bd95e)</samp>](https://redirect.github.com/unnoq/orpc/commit/bd95e77e)
- **server**: Optimize encodeHibernationRPCEvent  -  by
[@&#8203;unnoq](https://redirect.github.com/unnoq)
[<samp>(ec7d8)</samp>](https://redirect.github.com/unnoq/orpc/commit/ec7d8014)

#####    🐞 Bug Fixes

- **openapi**: OpenAPIGenerator make response headers optional when
headers object is optional  -  by
[@&#8203;unnoq](https://redirect.github.com/unnoq) in
[https://github.com/unnoq/orpc/issues/642](https://redirect.github.com/unnoq/orpc/issues/642)
[<samp>(5b223)</samp>](https://redirect.github.com/unnoq/orpc/commit/5b22383d)

#####     [View changes on
GitHub](https://redirect.github.com/unnoq/orpc/compare/v1.5.0...v1.5.1)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/mmkal/trpc-cli).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MC41MC4wIiwidXBkYXRlZEluVmVyIjoiNDAuNjIuMSIsInRhcmdldEJyYW5jaCI6ImRlcHMiLCJsYWJlbHMiOltdfQ==-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>